eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      # 유레카 서버가 어디에 있는지를 위치 정보를 여기다가 명시해 둔 것이다.
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://127.0.0.1:3306/Glemoa
    username: root
    password: yourpassword
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  expiration: 1000
  #  Base64로 인코딩된 문자 32자 이상 필요.(특수문자안됨) -> 재미나이 설명으로는 최소 88자 필요
  #  beyondaccesstokensecretkeybeyondaccesstokensecretkeybeyondaccesstokensecretkey
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

  expirationRt: 288000
  #  beyondrefreshtokensecretkeybeyondrefreshtokensecretkeybeyondrefreshtokensecretkey
  secretKeyRt: YmV5b25kcmVmcmVzaHRva2Vuc2VjcmV0a2V5YmV5b25kcmVmcmVzaHRva2Vuc2VjcmV0a2V5YmV5b25kcmVmcmVzaHRva2Vuc2VjcmV0a2V5

oauth:
  google:
    client-id: 1016866503845-g2stk5ilu15a3i4qj492md1lk85s76v4.apps.googleusercontent.com
    # 이 redirect-uri는 최초에 우리가 설정했던 uri가 어떤 건지를 다시 한번 증명하는 과정임.
    redirect-uri: http://localhost:3000/oauth/google/redirect
  kakao:
    client-id: 4c59ef5dce393223983be904010b1b73
    redirect-uri: http://localhost:3000/oauth/kakao/redirect